[build]
  publish = "."

[[redirects]]
  from = "/articles"
  to = "/articles/index.html"
  status = 301

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
